name: run generateBlockList.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' #Every 12h.
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.31.0 pillow==10.3.0
          
      - name: execute py script
        run: |
          cd ./blockIDs
          python ./blockIDs/generateBlockList.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "generateBlockList Action." --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
